name: weather_app
description: Wether app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  connectivity_plus: ^6.0.5
  dio: ^5.6.0
  permission_handler: ^11.3.1
  geolocator: ^13.0.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  path_provider: ^2.1.4
  hydrated_bloc: ^9.1.5
  built_value: ^8.9.2

  mockito: ^5.0.0
  bloc_test: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  built_value_generator: ^8.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/